name: 'Run App'

on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.301'
      - uses: nuget/setup-nuget@v1
      - name: Nuget Restore
        run: nuget restore GithubActions.sln
      - name: Install dependencies
        run: dotnet restore GithubActions.sln
      - name: Build
        run: msbuild /p:Configuration=Release GithubActions.sln
      - name: Run Unit Tests
        run: mono ./packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./Tests/bin/Release/Tests.dll